language: node_js
node_js:
- 8.11.3
cache:
  directories:
  - node_modules
env:
  global:
  - USER=postgres
  - DATABASE=stackoverflow
  - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct;
    else git log -1 --skip 1 --pretty=format:%ct; fi)
before_script:
- psql -c "CREATE DATABASE $DATABASE;" -U $USER
- psql -U $USER -d $DATABASE -a -f ./sql/tables.sql
addons:
  postgresql: '9.5'
  code_climate:
    repo_token:
      secure: noK1g8a8TaDLBRTYKMf2y+l4AE8XyjyyFhtPfhcnrlHmfhWvFItCsa7RQrWxOnany3/Nh0g7Uj4TAMw4IV7pUFvBzpfKJ2qAW6wdg8sN1JM2EhWezh1/M0UU8+5DYjgn0rxFqMs8r2Ur5K83vg0yYzoPASTQ1QKgwYEfCWZVHNeSp5jRzjC68/ZFRXcbBvU/sPP3NbOw+W/R4UvbyMrOyqz74PKybrUaghMeY5k29Jyp//9lxLE2XsmdSscTKaVvMPt0CJa+sxVHRah7nsLQRiZzEVywySN23RaWQwosW06VbEx58wtvJ6G0Om9D+vc6o7uRvIapm2zYQy0TbXOFkEW1lFgYpOiNzuqRrEEFYalf6XPqW1iwbyGgEQdlInxSjzDjU+02fQNx/pSygEzB4UHCQ94gBuo+QQzlVPv9bw0iYbgpE56CE/Zgk3fdUqtKSn32on7cqVhxYnPxdoTHyt2K5Fyge142hIp0BP8hLu919vOuDSfvKSUDLoOMVzbpPIWhu8Ga7XQIW1yjLtJ7IvK6ASzvwLa8Dc+DAIOz1w2eGXCUTp//i8XsWWLgi4sOamFchyLeWThKKoGeP8DzwR73bjuptUAisrc33fn9r3h6un5/nnHl4HN+USepix2rwHT2DzjrNhv7/2WAfzHntKJrwb8+UkeNonTlsuwQ7g4=
script:
- NODE_ENV=development npm run-script coverage
deploy:
  provider: heroku
  api_key:
    secure: mao/qZfLYftQ8m9bvcBhKJ98775pyCIqIXQpuK7+2Ru9K777sRZD5rB5I2EgmdQ9mqh+uevp4ZXDFW060vMMngTK/UMblgscZE+GokB/NzofuEwHGS44GTmXnU+4YRI3XiGwO5+DbGBOLV7uBl0NgYUm1MDmvWmZYXTZd0Y4SV3WLyuIOoK6ZO7OHfUuJj3E7mnvoEJ8X6P5Oz9FSxXN7p/l8VpGqo01vMi0F0YsLQD0uf5u1V1S+oy/tUzdILDTeqkVKIL2xmoez9axUcWEAwOPXrmYCngjAmwGH1URHmNYxX91qZbopNvOspfF7kJXD4jI3tGAV5gRRMvQuMmop8AAG4x9Ldu1CeQY61BNwXPpcHDBAgaboPe5v5vPI2jpmlEHX8LyUYohIl2h4BOLatGEBwy0tkDer1LeBQUdVobGM00DrAIlcr3xUHTP/r7WUTefQ2hGb3olJaZ2wmLujvllTFkJ8e3O7FW7nvRbZjZl0Mpt3LE81zTG7MffvFKEykQfNhYWy+x7LQ/fM5NChLqAzzwhm8MK0m1bAJLq5TPGL2t0P/4GN7HXWGZ2OLQJ0bnOVOYuAlw+ou1DYfYk1jryAtjRmzOwOHLtM9fOfUdXhEE82WqZFLICH1q4PBdeS+Gqet3GzDIDv1GuPTnEiCu04bC+Co8iQ08AjMDUnMM=
  app: stackoverflow-lite-api-node
  on:
    repo: Tiemma/stackoverflow-lite
    branch: develop
