language: python
python:
  - "3.5"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - FLASK_ENV=development
install: 
  - pip install pipenv
  - pipenv install --dev --three
script:
  - pipenv run -- py.test src/tests -s -v 
