language: node_js
node_js:
- 8.11.3
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=development
  - ENABLE_SSL=false
  - USER=postgres
  - DATABASE=stackoverflow
  - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct;
    else git log -1 --skip 1 --pretty=format:%ct; fi)
before_script:
- psql -c "CREATE DATABASE $DATABASE;" -U $USER
- psql -U $USER -d $DATABASE -a -f ./sql/tables.sql
addons:
  postgresql: '9.5'
  code_climate:
    repo_token:
      secure: noK1g8a8TaDLBRTYKMf2y+l4AE8XyjyyFhtPfhcnrlHmfhWvFItCsa7RQrWxOnany3/Nh0g7Uj4TAMw4IV7pUFvBzpfKJ2qAW6wdg8sN1JM2EhWezh1/M0UU8+5DYjgn0rxFqMs8r2Ur5K83vg0yYzoPASTQ1QKgwYEfCWZVHNeSp5jRzjC68/ZFRXcbBvU/sPP3NbOw+W/R4UvbyMrOyqz74PKybrUaghMeY5k29Jyp//9lxLE2XsmdSscTKaVvMPt0CJa+sxVHRah7nsLQRiZzEVywySN23RaWQwosW06VbEx58wtvJ6G0Om9D+vc6o7uRvIapm2zYQy0TbXOFkEW1lFgYpOiNzuqRrEEFYalf6XPqW1iwbyGgEQdlInxSjzDjU+02fQNx/pSygEzB4UHCQ94gBuo+QQzlVPv9bw0iYbgpE56CE/Zgk3fdUqtKSn32on7cqVhxYnPxdoTHyt2K5Fyge142hIp0BP8hLu919vOuDSfvKSUDLoOMVzbpPIWhu8Ga7XQIW1yjLtJ7IvK6ASzvwLa8Dc+DAIOz1w2eGXCUTp//i8XsWWLgi4sOamFchyLeWThKKoGeP8DzwR73bjuptUAisrc33fn9r3h6un5/nnHl4HN+USepix2rwHT2DzjrNhv7/2WAfzHntKJrwb8+UkeNonTlsuwQ7g4=
script:
- npm run-script coverage
deploy:
  provider: heroku
  api_key:
    secure: D+ts6VoqLE9o1cn7OPu9lXNLeLLqQXYyg1UJ3dJBqMCncLQxAvAvmawNqn+29JKaANjP3hlE+6IQT75eTjoYDaYlW7oxRrdV+8wJCblp793CdHP7otc3Amo2qeIwYiXednDwQTkIZB2vtnjvVhJCa1MHbVu7SnYNA1bOU57sORgCWDI8ZbMHMBIJFc3USavCb4WSQZkZoJZM+NAU1OtSu4Y/Pvab8LG2xjESA40ympr/3iqAHnP67lXBXVI6bIDg8Sb53nZ2zCSGXx/YXpltk2JyhcT/JmxnGPPXhpIXQXeHFU9TQ/g2BJzTs/24SRPUMAlPy/UdpR1Ibox0iq33+dvHSwoLsSU/lNGahs/7Xaj/TJgVHJfe379GO22C8vIMspjzDsg1fDY2OiHL+e2JAT6bcHu29aIBW3UKZIBP0EEZYlB3Dckx2u7RE6mv3lHNGbv2xqMIAuwob9dJBYT9RrbeZ4GTpBW0cYMKMiQC52s1JAmBH2DMq3ajbnyPEXPkxtDzoPbFuw0g9o0JYAWCqXB8zReBsFOPMqTlWEGcu6gVU0CV06SXtufmKxWQ/PkbZaZpiBtbHyERP6RQHylZ+LGlj/smuNFfzwTWnSfAjaoBi5ZxkhXRSx/0/w19AGB+aLeqjUlJiHcmOtN2weKUNbha9Wd/8TBePJ49lzIfRPc=
  app: stackoverflow-lite-api-node
  on:
    repo: Tiemma/stackoverflow-lite
    branch: develop
